### ISSUE TITLE
Add a Code of Conduct

### ISSUE THREAD

**Issue by oliverklee** [jjriv/emogrifier#299]
Like this: https://github.com/sebastianbergmann/phpunit/blob/master/CODE_OF_CONDUCT.md

**Comment by jjriv** [comment]
Definitely agree. Here is another good example:
https://github.com/schneems/postgresql/blob/master/CODE_OF_CONDUCT.md

____________________________________________________________________

John Reeve
jreeve@pelagodesign.com<mailto:jreeve@pelagodesign.com>
Intervals | Web-based Time, Task & Project Management | www.myintervals.com<http://www.myintervals.com>
____________________________________________________________________

**Comment by oliverklee** [comment]
@jjriv I'm currently working on this. I'd like to put a single email address in the document that forwards to both of us maintainers (me being github at oliverklee dot de). Would you be willing to set up such an email adress?

**Comment by jjriv** [comment]
Oliver,

I'd be happy to. I'm currently on vacation but send me the instructions on how to do this and I'll see if I can get to it. Otherwise, I can do it when I return on May 18th.

John

____________________________________________________________________

John Reeve
jreeve@pelagodesign.com<mailto:jreeve@pelagodesign.com>
Intervals | Web-based Time, Task & Project Management | www.myintervals.com<http://www.myintervals.com>
____________________________________________________________________

**Comment by oliverklee** [comment]
John,

I think you'll need to create an address at your email server that then redirects to both other email addresses. I propose the address maintainers AT emogrifier DOT com. What do you think?

**Comment by jjriv** [comment]
I don't have mail set up for emogrifier dot com. What about emogrifier AT myintervals DOT com? Or something to that effect? I can look into this when I return on the 18th, as it may take some setting up on the mail server side.

____________________________________________________________________

John Reeve
jreeve@pelagodesign.com<mailto:jreeve@pelagodesign.com>
Intervals | Web-based Time, Task & Project Management | www.myintervals.com<http://www.myintervals.com>
____________________________________________________________________

**Comment by oliverklee** [comment]
Yes, that email address looks fine, too!

**Comment by jjriv** [comment]
This is set up now. 
emogrifier at myintervals dot com
