### ISSUE TITLE
disableStyleBlocksParsing() doesn't seem to work.

### ISSUE THREAD

**Issue by BoilerTom90** [jjriv/emogrifier#357]
I'm using the disableStyleBlocksParsing() method before invoking emogrify(). The way I interpreted the documentation is that disableStyleBlocksParsing()  is suppose to leave the style blocks in the html document in addition to placing the styles inline. However, the later isn't happening. That is, the style blocks are left in the html document, but the CSS is not also inlined. 

If this is they way this is suppose to work, then I don't understand the purpose of this method.

**Comment by oliverklee** [comment]
Hi @BoilerTom90, the functionality is do basically just disable the emogrification (i.e., the conversion of style tags and style attributes). We implemented this in #155 and #156 as requested by @erikhansen.

@erikhansen Why did you need to disable the emogrification of the CSS while still using Emogrifier? (I'm asking because I'm not quite convinced that this actually makes sense.)

**Comment by erikhansen** [comment]
@oliverklee Magento 1 and Magento 2 use the Emogrifier library and depend heavily on the `disableStyleBlocksParsing` method. 

Email styles are split into two LESS files: Styles that are intended to be inlined by Emogrifier ([email-inline.less](https://github.com/magento/magento2/blob/2.1.3/app/design/frontend/Magento/blank/web/css/email-inline.less)) and "non-inline" styles that are intended to be included in a `<style>` block in the email `<head>` (for responsive styles, etc) ([email.less](https://github.com/magento/magento2/blob/2.1.3/app/design/frontend/Magento/blank/web/css/email.less)). The contents of the `email-inline.less` file get fed into the Emogrifier object using the `setCss` method and the contents of the `email.less` file get inserted into a `<style>` element in the email. You can see from this line of code that the Magento application calls the `disableStyleBlocksParsing` method so that the `<style>` block does not get parsed and used for inline styles: https://github.com/magento/magento2/blob/2.1.3/app/code/Magento/Email/Model/Template/Filter.php#L979 Does this make sense?

I re-read the `disableStyleBlocksParsing` [section of the readme](https://github.com/jjriv/emogrifier#options) and the wording seems pretty clear, but maybe it could be further clarified to avoid confusion.

**Comment by BoilerTom90** [comment]
@erikhansen I see why you needed that option/capability.  What I was hoping to achieve is the ability to retain the style sections as well as inline the styles. The reason for this is I know not all styles will be or can be supported for inlining (e.g. pseudo classes).  However, if the style sections are retained some email clients might be able to support the classes.  

Thanks everyone for the clarifications!

**Comment by oliverklee** [comment]
@erikhansen Thanks for the explanation! Would you be willing to create a PR that adds this explanation to the README so the rationale is more clear (particularly for people who don't know this use case yet)? That would be awesome. :heart:

**Comment by erikhansen** [comment]
@oliverklee You're most welcome. Submitted a PR to clarify the option: https://github.com/jjriv/emogrifier/pull/368
