### ISSUE TITLE
Inline "style" attribute should have the highest priority

### ISSUE THREAD

**Issue by MAYBUGgh** [jjriv/emogrifier#391]
In the browser inline styles override CSS's styles. Emogrifier replaces inline rules with ones from CSS instead. For example, I have an HTML-code:
`<div class="some_class" style="backgorund-image: /images/1.jpg;"></div>`
And CSS-code:
`.some_class{
    backgorund-image: url('/images/2.jpg');
}`
After emogrifying I have:
`<div class="some_class" style="backgorund-image: /images/2.jpg;"></div>`

**Comment by MAYBUGgh** [comment]
I've tried more combinations and it looks like problem is in my code not in emogrifier. I'll provide more information later.

**Comment by MAYBUGgh** [comment]
OK, I've found out some details. The problem is not in my code and not in the Emogrifier - it 's in user's corrupted HTML such as `<div class="some_class" class="another_class" style="backgorund-image: /images/1.jpg;"></div>`. In this case Emogrifier takes "background-image" (or any other style) from the last "class" attribute specified in the tag ("another_class" for the shown example) instead of inline "style" attribute's.
Donnow should we call it an issue, but the browser acts differently: it use inline attribute's styles even if multiple "class" attributes provided. I think it could be right to make Emogrifier act like browser.
Hope this information will help you to develop such a useful project. Thank you.

**Comment by oliverklee** [comment]
In that case, I'd say that the behavior is undefined, and it's okay for Emogrifier to work differently than a browser. (Or, in other words, garbage in, garbage out. ;-) )

Thanks for reporting this and doing the research! :heart:

**Comment by seltix5** [comment]
hi,
I found this problem too, the inline styles should not be replaced with the ones added from the classes (this is how browsers behave).
In my case this is important too because the basic styles area loaded from a CSS file and the custom styles are printed directly in the HTML.
The styles imported from the classes should be added BEFORE the already inline styles, or at least Emogrifier should have a option to control the insert position (before or after inline styles already in the html input).
Thanks!

**Comment by oliverklee** [comment]
@seltix5, #404 will fix this.
